excerpt_separator: "\n\n\n"
markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Tristan Foureur
production_url : http://esya.me
description: "Tristan Foureur"
disqus_shortname: esya
# analytics: UA-32899481-1
gauges: 50f1f940613f5d2cfe000026
author :
  name : Tristan Foureur
  github : esya
  twitter : esyacreations
  email: esya@me.com
