excerpt_separator: "\n\n\n"
markdown: kramdown
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Tristan Foureur
production_url : http://esya.me
url: http://www.esya.me
description: "Tristan Foureur"
disqus_shortname: esya
analytics: UA-43731968-1
author :
  name : Tristan Foureur
  github : esya
  twitter : tfoureur
  email: esya@me.com
